// The MCP marketplace (specs/tool-gateway): servers Orbis knows how to connect
// in one click, every one usable for free (no account, a free plan or a free
// key). Every npm package and endpoint here was checked to exist when it was
// added (npm registry, the package starting and listing its tools, a live
// endpoint answering `initialize`, OAuth servers publishing dynamic client
// registration). Logos: packages/web/public/logos/mcp (SOURCES.md).
import type { McpCatalogEntry } from "@orbis/shared";

const NODE = "Node.js (npx)";

export type CatalogEntry = McpCatalogEntry;

export const MCP_CATALOG: CatalogEntry[] = [
  // --- no account -------------------------------------------------------------------------
  {
    id: "deepwiki",
    name: "DeepWiki",
    icon: "📚",
    logo: "/logos/mcp/deepwiki.png",
    category: "dev",
    description: {
      en: "Documentation and answers about any public GitHub repository. No account.",
      "pt-BR": "Documentação e respostas sobre qualquer repositório público do GitHub. Sem conta.",
    },
    transport: "http",
    url: "https://mcp.deepwiki.com/mcp",
    auth: "none",
    fields: [],
    homepage: "https://deepwiki.com",
    readOnly: true,
  },
  {
    id: "exa",
    name: "Exa Search",
    icon: "🔎",
    logo: "/logos/mcp/exa.svg",
    category: "research",
    description: {
      en: "Web search and the text of pages, for research with sources. No account (with limits).",
      "pt-BR": "Busca na web e o texto das páginas, para pesquisar com fontes. Sem conta (com limites).",
    },
    transport: "http",
    url: "https://mcp.exa.ai/mcp",
    auth: "none",
    fields: [],
    homepage: "https://exa.ai",
    readOnly: true,
  },
  {
    id: "context7",
    name: "Context7",
    icon: "📖",
    logo: "/logos/mcp/context7.png",
    category: "dev",
    description: {
      en: "Up-to-date documentation and code examples of libraries and frameworks. No account.",
      "pt-BR": "Documentação atualizada e exemplos de código de bibliotecas e frameworks. Sem conta.",
    },
    transport: "http",
    url: "https://mcp.context7.com/mcp",
    auth: "none",
    fields: [],
    homepage: "https://context7.com",
    readOnly: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    icon: "🤗",
    logo: "/logos/mcp/huggingface.svg",
    category: "research",
    description: {
      en: "Search models, datasets, Spaces and papers on Hugging Face. A token is optional.",
      "pt-BR": "Busque modelos, datasets, Spaces e artigos no Hugging Face. O token é opcional.",
    },
    transport: "http",
    url: "https://huggingface.co/mcp",
    auth: "none",
    fields: [
      {
        key: "token",
        label: { en: "Access token (optional)", "pt-BR": "Token de acesso (opcional)" },
        secret: true,
        target: "bearer",
        placeholder: "hf_…",
        link: "https://huggingface.co/settings/tokens",
        optional: true,
      },
    ],
    homepage: "https://huggingface.co/settings/mcp",
    readOnly: true,
  },
  {
    id: "sequential-thinking",
    name: "Sequential Thinking",
    icon: "🧠",
    logo: "/logos/mcp/mcp.svg",
    category: "reasoning",
    description: {
      en: "A scratchpad for thinking a problem through step by step, revising and branching.",
      "pt-BR": "Um rascunho para pensar um problema passo a passo, revisando e ramificando.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    auth: "none",
    fields: [],
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    needs: NODE,
    readOnly: true,
  },
  {
    id: "playwright",
    name: "Playwright Browser",
    icon: "🎭",
    logo: "/logos/mcp/playwright.svg",
    category: "browser",
    description: {
      en: "A browser window the bot drives by the page's structure: click, type, fill forms, take screenshots.",
      "pt-BR": "Uma janela de navegador que o bot controla pela estrutura da página: clicar, digitar, preencher formulários, capturar a tela.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@playwright/mcp@latest"],
    auth: "none",
    fields: [],
    homepage: "https://github.com/microsoft/playwright-mcp",
    needs: NODE,
  },
  {
    id: "filesystem",
    name: "Filesystem",
    icon: "🗂️",
    logo: "/logos/mcp/mcp.svg",
    category: "files",
    description: {
      en: "Read, write, search and move files inside one folder of this computer that you choose.",
      "pt-BR": "Ler, gravar, buscar e mover arquivos dentro de uma pasta deste computador que você escolhe.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem"],
    auth: "none",
    fields: [
      {
        key: "folder",
        label: { en: "Folder it may use (full path)", "pt-BR": "Pasta que ele pode usar (caminho completo)" },
        secret: false,
        target: "arg",
        placeholder: "C:\\Users\\you\\Documents",
      },
    ],
    homepage: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    needs: NODE,
  },

  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    icon: "📘",
    logo: "/logos/mcp/microsoft-learn.svg",
    category: "dev",
    description: {
      en: "Official Microsoft documentation and code samples: Azure, .NET, Microsoft 365, Windows, Power Platform. No account.",
      "pt-BR": "Documentação oficial e exemplos de código da Microsoft: Azure, .NET, Microsoft 365, Windows, Power Platform. Sem conta.",
    },
    transport: "http",
    url: "https://learn.microsoft.com/api/mcp",
    auth: "none",
    fields: [],
    homepage: "https://learn.microsoft.com/training/support/mcp",
    readOnly: true,
  },
  {
    id: "aws-knowledge",
    name: "AWS Knowledge",
    icon: "☁️",
    logo: "/logos/mcp/aws-knowledge.svg",
    category: "dev",
    description: {
      en: "AWS documentation, What's New, blog posts and architecture guidance, always current. No account.",
      "pt-BR": "Documentação da AWS, novidades, posts do blog e guias de arquitetura, sempre atualizados. Sem conta.",
    },
    transport: "http",
    url: "https://knowledge-mcp.global.api.aws",
    auth: "none",
    fields: [],
    homepage: "https://awslabs.github.io/mcp/servers/aws-knowledge-mcp-server",
    readOnly: true,
  },
  {
    id: "cloudflare-docs",
    name: "Cloudflare Docs",
    icon: "🟠",
    logo: "/logos/mcp/cloudflare.svg",
    category: "dev",
    description: {
      en: "Search the Cloudflare documentation: Workers, Pages, R2, DNS, Zero Trust. No account.",
      "pt-BR": "Busca na documentação da Cloudflare: Workers, Pages, R2, DNS, Zero Trust. Sem conta.",
    },
    transport: "http",
    url: "https://docs.mcp.cloudflare.com/mcp",
    auth: "none",
    fields: [],
    homepage: "https://github.com/cloudflare/mcp-server-cloudflare",
    readOnly: true,
  },
  {
    id: "gitmcp",
    name: "GitMCP",
    icon: "🐙",
    logo: "/logos/mcp/gitmcp.png",
    category: "dev",
    description: {
      en: "The documentation and code of any public GitHub repository, read on demand. No account.",
      "pt-BR": "A documentação e o código de qualquer repositório público do GitHub, lidos na hora. Sem conta.",
    },
    transport: "http",
    url: "https://gitmcp.io/docs",
    auth: "none",
    fields: [],
    homepage: "https://gitmcp.io",
    readOnly: true,
  },
  {
    id: "coingecko",
    name: "CoinGecko",
    icon: "🦎",
    logo: "/logos/mcp/coingecko.png",
    category: "finance",
    description: {
      en: "Prices, market caps, charts and trends of cryptocurrencies, exchanges and NFTs. No account (public API limits).",
      "pt-BR": "Preços, valor de mercado, gráficos e tendências de criptomoedas, corretoras e NFTs. Sem conta (limites da API pública).",
    },
    transport: "http",
    url: "https://mcp.api.coingecko.com/mcp",
    auth: "none",
    fields: [],
    homepage: "https://docs.coingecko.com/reference/mcp-server",
    readOnly: true,
  },
  {
    id: "jina",
    name: "Jina AI Reader",
    icon: "🔍",
    logo: "/logos/mcp/jina.png",
    category: "research",
    description: {
      en: "Any web page as clean text, web and arXiv search, and screenshots of pages. No account; a free key raises the limits.",
      "pt-BR": "Qualquer página da web como texto limpo, busca na web e no arXiv e capturas de páginas. Sem conta; uma chave grátis aumenta os limites.",
    },
    transport: "http",
    url: "https://mcp.jina.ai/v1",
    auth: "none",
    fields: [
      {
        key: "token",
        label: { en: "Jina API key (optional)", "pt-BR": "Chave da API da Jina (opcional)" },
        secret: true,
        target: "bearer",
        placeholder: "jina_…",
        link: "https://jina.ai/api-dashboard/",
        optional: true,
      },
    ],
    homepage: "https://github.com/jina-ai/MCP",
    readOnly: true,
  },
  {
    id: "chrome-devtools",
    name: "Chrome DevTools",
    icon: "🛠️",
    logo: "/logos/mcp/chrome-devtools.svg",
    category: "browser",
    description: {
      en: "Drive and inspect a Chrome window: pages, clicks, forms, console, network requests, performance traces, Lighthouse.",
      "pt-BR": "Controlar e inspecionar uma janela do Chrome: páginas, cliques, formulários, console, requisições de rede, desempenho, Lighthouse.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "chrome-devtools-mcp@latest"],
    auth: "none",
    fields: [],
    needs: NODE,
    homepage: "https://github.com/ChromeDevTools/chrome-devtools-mcp",
  },
  {
    id: "youtube-transcript",
    name: "YouTube Transcript",
    icon: "▶️",
    logo: "/logos/mcp/youtube-transcript.svg",
    category: "research",
    description: {
      en: "The transcript (subtitles) of a YouTube video, in the language you ask for, to summarize or search it.",
      "pt-BR": "A transcrição (legendas) de um vídeo do YouTube, no idioma que você pedir, para resumir ou buscar nele.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@kimtaeyoon83/mcp-server-youtube-transcript"],
    auth: "none",
    fields: [],
    needs: NODE,
    homepage: "https://github.com/kimtaeyoon83/mcp-server-youtube-transcript",
    readOnly: true,
  },
  {
    id: "excel",
    name: "Excel",
    icon: "📊",
    logo: "/logos/mcp/excel.svg",
    category: "files",
    description: {
      en: "Read and write Excel workbooks (.xlsx) on this computer: sheets, ranges, formulas, tables and formatting.",
      "pt-BR": "Ler e gravar planilhas do Excel (.xlsx) neste computador: abas, intervalos, fórmulas, tabelas e formatação.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@negokaz/excel-mcp-server"],
    auth: "none",
    fields: [],
    needs: NODE,
    homepage: "https://github.com/negokaz/excel-mcp-server",
  },

  // --- sign in with your account ---------------------------------------------------------------
  {
    id: "notion",
    name: "Notion",
    icon: "📝",
    logo: "/logos/mcp/notion.svg",
    category: "work",
    description: {
      en: "Search, read, create and update pages and databases in your Notion workspace.",
      "pt-BR": "Buscar, ler, criar e atualizar páginas e bancos de dados do seu Notion.",
    },
    transport: "http",
    url: "https://mcp.notion.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://developers.notion.com/docs/mcp",
  },
  {
    id: "linear",
    name: "Linear",
    icon: "📐",
    logo: "/logos/mcp/linear.svg",
    category: "work",
    description: {
      en: "Find, create and update issues, projects and comments in Linear.",
      "pt-BR": "Encontrar, criar e atualizar issues, projetos e comentários no Linear.",
    },
    transport: "http",
    url: "https://mcp.linear.app/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://linear.app/docs/mcp",
  },
  {
    id: "atlassian",
    name: "Jira & Confluence",
    icon: "🧭",
    logo: "/logos/mcp/atlassian.svg",
    category: "work",
    description: {
      en: "Jira issues and Confluence pages of your Atlassian site: search, create, update, comment.",
      "pt-BR": "Issues do Jira e páginas do Confluence do seu site Atlassian: buscar, criar, atualizar, comentar.",
    },
    transport: "http",
    url: "https://mcp.atlassian.com/v1/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://support.atlassian.com/rovo/docs/getting-started-with-the-atlassian-remote-mcp-server/",
  },
  {
    id: "sentry",
    name: "Sentry",
    icon: "🐞",
    logo: "/logos/mcp/sentry.svg",
    category: "dev",
    description: {
      en: "Errors, issues and releases of your Sentry projects, with stack traces.",
      "pt-BR": "Erros, issues e releases dos seus projetos no Sentry, com stack traces.",
    },
    transport: "http",
    url: "https://mcp.sentry.dev/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://docs.sentry.io/product/sentry-mcp/",
  },
  {
    id: "supabase",
    name: "Supabase",
    icon: "🟢",
    logo: "/logos/mcp/supabase.svg",
    category: "dev",
    description: {
      en: "Your Supabase projects: tables, SQL, migrations, logs and edge functions.",
      "pt-BR": "Seus projetos Supabase: tabelas, SQL, migrations, logs e edge functions.",
    },
    transport: "http",
    url: "https://mcp.supabase.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://supabase.com/docs/guides/getting-started/mcp",
  },
  {
    id: "canva",
    name: "Canva",
    icon: "🎨",
    logo: "/logos/mcp/canva.png",
    category: "work",
    description: {
      en: "Find, create and export designs in your Canva account.",
      "pt-BR": "Encontrar, criar e exportar designs da sua conta Canva.",
    },
    transport: "http",
    url: "https://mcp.canva.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://www.canva.dev/docs/mcp/",
  },

  {
    id: "todoist",
    name: "Todoist",
    icon: "✅",
    logo: "/logos/mcp/todoist.svg",
    category: "work",
    description: {
      en: "Your Todoist tasks and projects: add, find, update and complete tasks. Free plan.",
      "pt-BR": "Suas tarefas e projetos do Todoist: criar, buscar, atualizar e concluir tarefas. Plano gratuito.",
    },
    transport: "http",
    url: "https://ai.todoist.net/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://www.todoist.com/help/articles/use-todoist-with-ai-tools",
  },
  {
    id: "monday",
    name: "monday.com",
    icon: "📅",
    logo: "/logos/mcp/monday.png",
    category: "work",
    description: {
      en: "Boards, items, updates and people of your monday.com workspace. Free plan.",
      "pt-BR": "Quadros, itens, atualizações e pessoas do seu monday.com. Plano gratuito.",
    },
    transport: "http",
    url: "https://mcp.monday.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://developer.monday.com/apps/docs/mondaycom-mcp-integration",
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: "▲",
    logo: "/logos/mcp/vercel.svg",
    category: "dev",
    description: {
      en: "Your Vercel projects and deployments: logs, domains and the Vercel docs. Free Hobby plan.",
      "pt-BR": "Seus projetos e deploys na Vercel: logs, domínios e a documentação da Vercel. Plano Hobby gratuito.",
    },
    transport: "http",
    url: "https://mcp.vercel.com",
    auth: "oauth",
    fields: [],
    homepage: "https://vercel.com/docs/mcp/vercel-mcp",
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers",
    icon: "🟠",
    logo: "/logos/mcp/cloudflare.svg",
    category: "dev",
    description: {
      en: "Your Cloudflare account: Workers, KV, R2 and D1 — list, create and query them. Free plan.",
      "pt-BR": "Sua conta da Cloudflare: Workers, KV, R2 e D1 — listar, criar e consultar. Plano gratuito.",
    },
    transport: "http",
    url: "https://bindings.mcp.cloudflare.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://github.com/cloudflare/mcp-server-cloudflare",
  },
  {
    id: "neon",
    name: "Neon Postgres",
    icon: "🐘",
    logo: "/logos/mcp/neon.svg",
    category: "dev",
    description: {
      en: "Your Neon Postgres databases: projects, branches, schemas and SQL queries. Free plan.",
      "pt-BR": "Seus bancos Postgres na Neon: projetos, branches, esquemas e consultas SQL. Plano gratuito.",
    },
    transport: "http",
    url: "https://mcp.neon.tech/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://neon.com/docs/ai/neon-mcp-server",
  },
  {
    id: "prisma",
    name: "Prisma Postgres",
    icon: "🔺",
    logo: "/logos/mcp/prisma.svg",
    category: "dev",
    description: {
      en: "Create and manage Prisma Postgres databases, run migrations and query them. Free plan.",
      "pt-BR": "Criar e gerenciar bancos Prisma Postgres, rodar migrações e consultar. Plano gratuito.",
    },
    transport: "http",
    url: "https://mcp.prisma.io/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://www.prisma.io/docs/postgres/integrations/mcp-server",
  },
  {
    id: "postman",
    name: "Postman",
    icon: "📮",
    logo: "/logos/mcp/postman.svg",
    category: "dev",
    description: {
      en: "Your Postman workspaces, collections, environments and API specs. Free plan.",
      "pt-BR": "Seus workspaces, coleções, ambientes e especificações de API no Postman. Plano gratuito.",
    },
    transport: "http",
    url: "https://mcp.postman.com/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://learning.postman.com/docs/developer/postman-api/postman-mcp-server/",
  },
  {
    id: "semgrep",
    name: "Semgrep",
    icon: "🛡️",
    logo: "/logos/mcp/semgrep.svg",
    category: "dev",
    description: {
      en: "Scan code for security bugs and vulnerable dependencies with Semgrep's rules. Free for individuals.",
      "pt-BR": "Varrer o código atrás de falhas de segurança e dependências vulneráveis com as regras do Semgrep. Grátis para uso individual.",
    },
    transport: "http",
    url: "https://mcp.semgrep.ai/mcp",
    auth: "oauth",
    fields: [],
    homepage: "https://semgrep.dev/docs/mcp",
  },
  {
    id: "stripe",
    name: "Stripe",
    icon: "💳",
    logo: "/logos/mcp/stripe.svg",
    category: "finance",
    description: {
      en: "Your Stripe account: customers, payments, invoices, products and the Stripe docs (test mode is free).",
      "pt-BR": "Sua conta Stripe: clientes, pagamentos, faturas, produtos e a documentação da Stripe (o modo de teste é grátis).",
    },
    transport: "http",
    url: "https://mcp.stripe.com",
    auth: "oauth",
    fields: [],
    homepage: "https://docs.stripe.com/mcp",
  },

  // --- a key or token ----------------------------------------------------------------------------
  {
    id: "github",
    name: "GitHub",
    icon: "🐙",
    logo: "/logos/mcp/github.svg",
    category: "dev",
    description: {
      en: "Repositories, issues, pull requests, code search and Actions, with your personal access token.",
      "pt-BR": "Repositórios, issues, pull requests, busca de código e Actions, com o seu token de acesso pessoal.",
    },
    transport: "http",
    url: "https://api.githubcopilot.com/mcp/",
    auth: "token",
    fields: [
      {
        key: "token",
        label: { en: "Personal access token", "pt-BR": "Token de acesso pessoal" },
        secret: true,
        target: "bearer",
        placeholder: "github_pat_…",
        help: {
          en: "Create a fine-grained token with access to the repositories the bots may use.",
          "pt-BR": "Crie um token fine-grained com acesso aos repositórios que os bots podem usar.",
        },
        link: "https://github.com/settings/personal-access-tokens/new",
      },
    ],
    homepage: "https://github.com/github/github-mcp-server",
  },
  {
    id: "brave-search",
    name: "Brave Search",
    icon: "🦁",
    logo: "/logos/mcp/brave-search.svg",
    category: "research",
    description: {
      en: "Web, news, image and local search with the Brave Search API (free plan available).",
      "pt-BR": "Busca na web, notícias, imagens e locais com a API do Brave Search (tem plano gratuito).",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "@brave/brave-search-mcp-server"],
    auth: "token",
    fields: [
      {
        key: "BRAVE_API_KEY",
        label: { en: "Brave Search API key", "pt-BR": "Chave da API do Brave Search" },
        secret: true,
        target: "env",
        link: "https://brave.com/search/api/",
      },
    ],
    homepage: "https://github.com/brave/brave-search-mcp-server",
    needs: NODE,
    readOnly: true,
  },
  {
    id: "tavily",
    name: "Tavily",
    icon: "🛰️",
    logo: "/logos/mcp/tavily.svg",
    category: "research",
    description: {
      en: "Search built for AI agents, and the extracted content of pages (free credits every month).",
      "pt-BR": "Busca feita para agentes de IA e o conteúdo extraído das páginas (créditos grátis todo mês).",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "tavily-mcp"],
    auth: "token",
    fields: [
      {
        key: "TAVILY_API_KEY",
        label: { en: "Tavily API key", "pt-BR": "Chave da API da Tavily" },
        secret: true,
        target: "env",
        placeholder: "tvly-…",
        link: "https://app.tavily.com",
      },
    ],
    homepage: "https://github.com/tavily-ai/tavily-mcp",
    needs: NODE,
    readOnly: true,
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    icon: "🔥",
    logo: "/logos/mcp/firecrawl.png",
    category: "research",
    description: {
      en: "Scrape and crawl websites into clean text, including pages that need a browser.",
      "pt-BR": "Extrair e percorrer sites em texto limpo, inclusive páginas que precisam de navegador.",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "firecrawl-mcp"],
    auth: "token",
    fields: [
      {
        key: "FIRECRAWL_API_KEY",
        label: { en: "Firecrawl API key", "pt-BR": "Chave da API do Firecrawl" },
        secret: true,
        target: "env",
        placeholder: "fc-…",
        link: "https://www.firecrawl.dev/app/api-keys",
      },
    ],
    homepage: "https://github.com/firecrawl/firecrawl-mcp-server",
    needs: NODE,
    readOnly: true,
  },
  {
    id: "alphavantage",
    name: "Alpha Vantage",
    icon: "📈",
    logo: "/logos/mcp/alphavantage.png",
    category: "finance",
    description: {
      en: "Stock, ETF, forex and crypto quotes and history, company fundamentals, news sentiment and technical indicators (free key).",
      "pt-BR": "Cotações e histórico de ações, ETFs, câmbio e cripto, fundamentos de empresas, sentimento de notícias e indicadores técnicos (chave grátis).",
    },
    transport: "http",
    url: "https://mcp.alphavantage.co/mcp",
    auth: "token",
    fields: [
      {
        key: "apikey",
        label: { en: "Alpha Vantage API key", "pt-BR": "Chave da API da Alpha Vantage" },
        secret: true,
        target: "query",
        help: { en: "Free: claim one with your e-mail.", "pt-BR": "Grátis: peça uma com o seu e-mail." },
        link: "https://www.alphavantage.co/support/#api-key",
      },
    ],
    homepage: "https://mcp.alphavantage.co",
    readOnly: true,
  },
  {
    id: "airtable",
    name: "Airtable",
    icon: "🗃️",
    logo: "/logos/mcp/airtable.svg",
    category: "work",
    description: {
      en: "Your Airtable bases: tables, fields and records — list, search, create and update them (free plan).",
      "pt-BR": "Suas bases do Airtable: tabelas, campos e registros — listar, buscar, criar e atualizar (plano gratuito).",
    },
    transport: "stdio",
    command: "npx",
    args: ["-y", "airtable-mcp-server"],
    auth: "token",
    fields: [
      {
        key: "AIRTABLE_API_KEY",
        label: { en: "Airtable personal access token", "pt-BR": "Token de acesso pessoal do Airtable" },
        secret: true,
        target: "env",
        placeholder: "pat…",
        help: {
          en: "Give it the scopes schema.bases:read, data.records:read (and :write to let bots change records).",
          "pt-BR": "Dê os escopos schema.bases:read, data.records:read (e :write para os bots alterarem registros).",
        },
        link: "https://airtable.com/create/tokens",
      },
    ],
    homepage: "https://github.com/domdomegg/airtable-mcp-server",
    needs: NODE,
  },

  // --- marketing: ads, analytics and social accounts ----------------------------------------
  {
    id: "meta-ads",
    name: "Meta Ads",
    icon: "📣",
    logo: "/logos/mcp/meta-ads.svg",
    category: "marketing",
    description: {
      en: "Meta's official server: your Facebook and Instagram ad accounts — campaigns, ad sets, ads, audiences, results (insights), leads and comments. Sign in with your Meta Business account.",
      "pt-BR": "Servidor oficial da Meta: suas contas de anúncio do Facebook e do Instagram — campanhas, conjuntos, anúncios, públicos, resultados (insights), leads e comentários. Entre com a sua conta Meta Business.",
    },
    transport: "http",
    url: "https://mcp.facebook.com/ads",
    auth: "oauth",
    fields: [],
    homepage: "https://developers.facebook.com/documentation/ads-commerce/ads-ai-connectors/ads-mcp-server/ads-mcp-server-overview",
  },
  {
    id: "tiktok-ads",
    name: "TikTok Ads",
    icon: "🎵",
    logo: "/logos/mcp/tiktok-ads.svg",
    category: "marketing",
    description: {
      en: "TikTok's official server: campaigns, ad groups, ads, reports, audiences and catalogs of your TikTok for Business account, about 40 tools that find the rest when needed. Sign in again every 30 days.",
      "pt-BR": "Servidor oficial do TikTok: campanhas, grupos de anúncios, anúncios, relatórios, públicos e catálogos da sua conta TikTok for Business, cerca de 40 ferramentas que acham as demais quando precisa. Entre de novo a cada 30 dias.",
    },
    transport: "http",
    // The progressive endpoint: ~40 tools up front instead of ~400 in every bot's context.
    url: "https://business-api.tiktok.com/open_mcp/tt-ads-mcp-layer",
    auth: "oauth",
    fields: [],
    homepage: "https://business-api.tiktok.com/portal/docs/tiktok-ads-mcp-server/v1.3",
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    icon: "📊",
    logo: "/logos/mcp/google-analytics.svg",
    category: "marketing",
    description: {
      en: "Google's official server, read-only: your GA4 accounts and properties, reports, real-time, funnels and conversions. Needs a Google credentials file with the Analytics read-only scope.",
      "pt-BR": "Servidor oficial do Google, só leitura: suas contas e propriedades do GA4, relatórios, tempo real, funis e conversões. Precisa de um arquivo de credenciais do Google com o escopo de leitura do Analytics.",
    },
    transport: "stdio",
    command: "pipx",
    args: ["run", "analytics-mcp"],
    auth: "token",
    fields: [
      {
        key: "GOOGLE_APPLICATION_CREDENTIALS",
        label: { en: "Google credentials file (path to the JSON)", "pt-BR": "Arquivo de credenciais do Google (caminho do JSON)" },
        secret: false,
        target: "env",
        placeholder: "/root/.config/gcloud/application_default_credentials.json",
        help: {
          en: "The file `gcloud auth application-default login --scopes https://www.googleapis.com/auth/analytics.readonly,https://www.googleapis.com/auth/cloud-platform` saves, or a service account's key added as a Viewer of your GA4 property.",
          "pt-BR": "O arquivo que `gcloud auth application-default login --scopes https://www.googleapis.com/auth/analytics.readonly,https://www.googleapis.com/auth/cloud-platform` salva, ou a chave de uma conta de serviço adicionada como Leitor da sua propriedade do GA4.",
        },
        link: "https://github.com/googleanalytics/google-analytics-mcp#configure-credentials-",
      },
      {
        key: "GOOGLE_PROJECT_ID",
        label: { en: "Google Cloud project ID", "pt-BR": "ID do projeto no Google Cloud" },
        secret: false,
        target: "env",
        placeholder: "my-project-123",
        help: {
          en: "The project where the Analytics Admin and Data APIs are enabled.",
          "pt-BR": "O projeto onde as APIs Analytics Admin e Analytics Data estão ativadas.",
        },
        link: "https://support.google.com/googleapi/answer/7014113",
      },
    ],
    homepage: "https://github.com/googleanalytics/google-analytics-mcp",
    needs: "Python (pipx)",
    readOnly: true,
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "📸",
    logo: "/logos/mcp/instagram.svg",
    category: "marketing",
    description: {
      en: "Your Instagram Business or Creator account through Meta's Graph API: profile, posts and their insights, account insights, comments, mentions, hashtags and stories. It can also publish, reply and send DMs, each asking you first. A community server (mcpware), pinned to a checked version.",
      "pt-BR": "Sua conta Comercial ou de Criador do Instagram pela Graph API da Meta: perfil, posts e os insights de cada um, insights da conta, comentários, menções, hashtags e stories. Também pode publicar, responder e mandar DM, sempre pedindo sua aprovação antes. Servidor da comunidade (mcpware), fixado numa versão verificada.",
    },
    transport: "stdio",
    command: "npx",
    // A community package holding a token that can post and send DMs: pinned to the version that was read.
    args: ["-y", "@mcpware/instagram-mcp@1.0.4"],
    auth: "token",
    fields: [
      {
        key: "INSTAGRAM_ACCESS_TOKEN",
        label: { en: "Meta long-lived access token", "pt-BR": "Token de acesso de longa duração da Meta" },
        secret: true,
        target: "env",
        help: {
          en: "From a Meta developer app, with instagram_basic, instagram_manage_insights, pages_show_list and pages_read_engagement (add instagram_content_publish, instagram_manage_comments or instagram_manage_messages only if the bot may post, answer comments or DMs). It lasts 60 days.",
          "pt-BR": "De um app de desenvolvedor da Meta, com instagram_basic, instagram_manage_insights, pages_show_list e pages_read_engagement (adicione instagram_content_publish, instagram_manage_comments ou instagram_manage_messages só se o bot puder postar, responder comentários ou DMs). Vale por 60 dias.",
        },
        link: "https://github.com/mcpware/instagram-mcp#setup-guide--getting-your-access-token",
      },
      {
        key: "INSTAGRAM_ACCOUNT_ID",
        label: { en: "Instagram Business account ID", "pt-BR": "ID da conta comercial do Instagram" },
        secret: false,
        target: "env",
        placeholder: "17841400000000000",
        help: {
          en: "The account must be Business or Creator and linked to a Facebook Page; the setup page shows how to find its ID.",
          "pt-BR": "A conta precisa ser Comercial ou de Criador e estar ligada a uma Página do Facebook; a página de configuração mostra como achar o ID.",
        },
        link: "https://github.com/mcpware/instagram-mcp#step-5-get-your-instagram-business-account-id",
      },
    ],
    homepage: "https://github.com/mcpware/instagram-mcp",
    needs: NODE,
  },

  // --- your files in the cloud ---------------------------------------------------------------
  {
    id: "google-drive",
    name: "Google Drive",
    icon: "🗂️",
    logo: "/logos/mcp/google-drive.svg",
    category: "files",
    description: {
      en: "Your Google Drive, with a personal or Workspace account: search and read files, Docs, Sheets and Slides, and create files and folders. You sign in through Orbis with your own Google OAuth client (free, in Google Cloud). A community server (piotr-agier), pinned to a checked version.",
      "pt-BR": "Seu Google Drive, com conta pessoal ou Workspace: buscar e ler arquivos, Docs, Planilhas e Apresentações, e criar arquivos e pastas. Você entra pelo Orbis com o seu próprio cliente OAuth do Google (grátis, no Google Cloud). Servidor da comunidade (piotr-agier), fixado numa versão verificada.",
    },
    transport: "stdio",
    command: "npx",
    // A community package that receives a Google sign-in: pinned to the version that was read.
    args: ["-y", "@piotr-agier/google-drive-mcp@2.12.0"],
    auth: "oauth",
    fields: [
      {
        key: "client_id",
        label: { en: "Google OAuth client ID", "pt-BR": "ID do cliente OAuth do Google" },
        secret: false,
        target: "client_id",
        placeholder: "123456789-abc.apps.googleusercontent.com",
        help: {
          en: "In Google Cloud: enable the Google Drive API, set up the OAuth consent screen (add yourself as a test user) and create an OAuth client of type Desktop app.",
          "pt-BR": "No Google Cloud: ative a Google Drive API, configure a tela de consentimento OAuth (adicione você como usuário de teste) e crie um cliente OAuth do tipo App para computador.",
        },
        link: "https://github.com/piotr-agier/google-drive-mcp/blob/main/docs/setup.md",
      },
      {
        key: "client_secret",
        label: { en: "Google OAuth client secret", "pt-BR": "Chave secreta do cliente OAuth do Google" },
        secret: true,
        target: "client_secret",
        placeholder: "GOCSPX-…",
      },
    ],
    oauth: {
      authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenEndpoint: "https://oauth2.googleapis.com/token",
      // Read all of Drive; write only the files it creates (Google's own Drive MCP asks for the same two).
      scope: "https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.file",
      // A refresh token, so the sign-in lasts beyond the hour.
      params: { access_type: "offline", prompt: "consent" },
      env: {
        accessToken: "GOOGLE_DRIVE_MCP_ACCESS_TOKEN",
        refreshToken: "GOOGLE_DRIVE_MCP_REFRESH_TOKEN",
        clientId: "GOOGLE_DRIVE_MCP_CLIENT_ID",
        clientSecret: "GOOGLE_DRIVE_MCP_CLIENT_SECRET",
      },
    },
    homepage: "https://github.com/piotr-agier/google-drive-mcp",
    needs: NODE,
  },
  {
    id: "onedrive",
    name: "OneDrive",
    icon: "☁️",
    logo: "/logos/mcp/onedrive.svg",
    category: "files",
    description: {
      en: "Your OneDrive, with a personal Microsoft account (Outlook, Hotmail) or a work one: search, read, upload, move and share files and folders. To sign in, ask a bot to log in to OneDrive and type the code it gives you on Microsoft's page. A community server (Softeria), OneDrive tools only, pinned to a checked version.",
      "pt-BR": "Seu OneDrive, com conta Microsoft pessoal (Outlook, Hotmail) ou de trabalho: buscar, ler, enviar, mover e compartilhar arquivos e pastas. Para entrar, peça a um bot para fazer login no OneDrive e digite na página da Microsoft o código que ele te der. Servidor da comunidade (Softeria), só as ferramentas do OneDrive, fixado numa versão verificada.",
    },
    transport: "stdio",
    command: "npx",
    // Microsoft 365 for one app only (the onedrive preset); pinned to the version that was read.
    args: ["-y", "@softeria/ms-365-mcp-server@0.158.0", "--preset", "onedrive"],
    auth: "device",
    fields: [],
    homepage: "https://github.com/Softeria/ms-365-mcp-server",
    needs: NODE,
  },
];

export function catalogEntry(id: string): CatalogEntry | undefined {
  return MCP_CATALOG.find((e) => e.id === id);
}
